
export const COUNTRY_CODES = [
  // Arab Countries
  { code: '+966', name: 'المملكة العربية السعودية', flag: '🇸🇦', country: 'SA' },
  { code: '+971', name: 'الإمارات العربية المتحدة', flag: '🇦🇪', country: 'AE' },
  { code: '+965', name: 'الكويت', flag: '🇰🇼', country: 'KW' },
  { code: '+974', name: 'قطر', flag: '🇶🇦', country: 'QA' },
  { code: '+968', name: 'عمان', flag: '🇴🇲', country: 'OM' },
  { code: '+973', name: 'البحرين', flag: '🇧🇭', country: 'BH' },
  { code: '+20', name: 'مصر', flag: '🇪🇬', country: 'EG' },
  { code: '+962', name: 'الأردن', flag: '🇯🇴', country: 'JO' },
  { code: '+961', name: 'لبنان', flag: '🇱🇧', country: 'LB' },
  { code: '+964', name: 'العراق', flag: '🇮🇶', country: 'IQ' },
  { code: '+212', name: 'المغرب', flag: '🇲🇦', country: 'MA' },
  { code: '+213', name: 'الجزائر', flag: '🇩🇿', country: 'DZ' },
  { code: '+216', name: 'تونس', flag: '🇹🇳', country: 'TN' },
  { code: '+218', name: 'ليبيا', flag: '🇱🇾', country: 'LY' },
  { code: '+967', name: 'اليمن', flag: '🇾🇪', country: 'YE' },
  { code: '+970', name: 'فلسطين', flag: '🇵🇸', country: 'PS' },
  { code: '+963', name: 'سوريا', flag: '🇸🇾', country: 'SY' },
  { code: '+249', name: 'السودان', flag: '🇸🇩', country: 'SD' },
  
  // Europe
  { code: '+44', name: 'المملكة المتحدة', flag: '🇬🇧', country: 'GB' },
  { code: '+49', name: 'ألمانيا', flag: '🇩🇪', country: 'DE' },
  { code: '+33', name: 'فرنسا', flag: '🇫🇷', country: 'FR' },
  { code: '+39', name: 'إيطاليا', flag: '🇮🇹', country: 'IT' },
  { code: '+34', name: 'إسبانيا', flag: '🇪🇸', country: 'ES' },
  { code: '+31', name: 'هولندا', flag: '🇳🇱', country: 'NL' },
  { code: '+46', name: 'السويد', flag: '🇸🇪', country: 'SE' },
  { code: '+47', name: 'النرويج', flag: '🇳🇴', country: 'NO' },
  { code: '+41', name: 'سويسرا', flag: '🇨🇭', country: 'CH' },
  { code: '+90', name: 'تركيا', flag: '🇹🇷', country: 'TR' },
  { code: '+32', name: 'بلجيكا', flag: '🇧🇪', country: 'BE' },
  { code: '+43', name: 'النمسا', flag: '🇦🇹', country: 'AT' },
  { code: '+351', name: 'البرتغال', flag: '🇵🇹', country: 'PT' },
  { code: '+30', name: 'اليونان', flag: '🇬🇷', country: 'GR' },
  { code: '+45', name: 'الدنمارك', flag: '🇩🇰', country: 'DK' },
  { code: '+358', name: 'فنلندا', flag: '🇫🇮', country: 'FI' },
  { code: '+353', name: 'أيرلندا', flag: '🇮🇪', country: 'IE' },
  
  // Americas & Others
  { code: '+1', name: 'الولايات المتحدة / كندا', flag: '🇺🇸', country: 'US' },
  { code: '+52', name: 'المكسيك', flag: '🇲🇽', country: 'MX' },
  { code: '+55', name: 'البرازيل', flag: '🇧🇷', country: 'BR' },
  { code: '+54', name: 'الأرجنتين', flag: '🇦🇷', country: 'AR' },
  { code: '+56', name: 'تشيلي', flag: '🇨🇱', country: 'CL' },
  { code: '+57', name: 'كولومبيا', flag: '🇨🇴', country: 'CO' },
  { code: '+7', name: 'روسيا', flag: '🇷🇺', country: 'RU' },
  { code: '+86', name: 'الصين', flag: '🇨🇳', country: 'CN' },
  { code: '+91', name: 'الهند', flag: '🇮🇳', country: 'IN' },
  { code: '+81', name: 'اليابان', flag: '🇯🇵', country: 'JP' },
  { code: '+82', name: 'كوريا الجنوبية', flag: '🇰🇷', country: 'KR' },
  { code: '+61', name: 'أستراليا', flag: '🇦🇺', country: 'AU' },
];
